### ISSUE TITLE
React-native 0.57.x

### ISSUE THREAD

**Issue by Kaitsuvaan** [januslo/react-native-bluetooth-escpos-printer#13]
Can you make this work newest react-native... thx

**Comment by januslo** [comment]
what's problem with 0.57.x?

发自我的 iPhone

**Comment by Kaitsuvaan** [comment]
* What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find any version that matches com.facebook.react:react-native:0.55+.
  Versions that do not match:
      0.20.1
      0.20.0
      0.19.1
      0.19.0
      0.18.0
      + 13 more
  Searched in the following locations:

**Comment by firdaussoberi** [comment]
Hi, I had the same problem before. I solved it by directly changing build.gradle in node_modules/react-native-bluetooth-escpos-printer/android. There is a line that require react-native ver 0.55+ . Change it to 0.57+  and u shud be fine

**Comment by januslo** [comment]
thx @firdaussoberi , duplicate with  https://github.com/januslo/react-native-bluetooth-escpos-printer/issues/5

**Comment by Kaitsuvaan** [comment]
@firdaussoberi hmm... works but get new errors :D 

> Task :react-native-bluetooth-escpos-printer:compileDebugJavaWithJavac FAILED
XXXXX\node_modules\react-native-bluetooth-escpos-printer\android\src\main\java\cn\jystudio\bluetooth\escpos\RNBluetoothEscposPrinterModule.java:10: error: package cn.jystudio.bluetooth.escpos.command.sdk does not exist
import cn.jystudio.bluetooth.escpos.command.sdk.Command;
                                               XXXX\node_modules\react-native-bluetooth-escpos-printer\android\src\main\java\cn\jystudio\bluetooth\escpos\RNBluetoothEscposPrinterModule.java:11: error: package cn.jystudio.bluetooth.escpos.command.sdk does not exist
import cn.jystudio.bluetooth.escpos.command.sdk.PrintPicture;
                                               ^

**Comment by januslo** [comment]
Sure you linked?


发自我的 iPhone

**Comment by firdaussoberi** [comment]
Yeah, i think u should ```react-native link``` after changing the build.gradle. Sometimes other errors like in local android/MainApplication. java and AndroidManifest.xml pops up but that's just about it

**Comment by GanongLS** [comment]
so this library was long long dead

**Comment by firdaussoberi** [comment]
> so this library was long long dead

More like peacefully dormant but yeah I'd agree it needs fresh updates. Maybe author is busy. So far still using it with both android/ios and works with RN0.60

**Comment by GanongLS** [comment]
somebody that know android development, please update this library, there is problem with react-native-bluetooth-escpos-printer/android/build.gradle

apply plugin: 'com.android.library'

android {
    compileSdkVersion 27 //this need to be update to 28
    buildToolsVersion "27.0.3" //this need to be update to 28.0.3

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
    sourceSets {
        main {
            aidl.srcDirs = ['src/main/java']
        }
    }
}

repositories {
    jcenter { url "http://jcenter.bintray.com/" }
    maven {url "http://repo.spring.io/plugins-release/"}
    mavenCentral()
    maven {
        // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
        url "$rootDir/../node_modules/react-native/android"
    }
    maven {
        url 'https://maven.google.com'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])// this need to change be implementation
    implementation 'com.facebook.react:react-native:+'  // From node_modules
    implementation group: 'com.android.support', name: 'support-v4', version: '27.0.0'
    implementation "com.google.zxing:core:3.3.0"
}
